<?php
$z[0]=Array("type","\r\n				    <li><a href=\"[field:typelink/]\">New products</a></li>\r\n				    ",608,716);
$z[0][4]=array();
$z[0][4]['typeid']="8";
$z[1]=Array("type","\r\n				    <li><a href=\"[field:typelink/]\">Baby sweater</a></li>\r\n				    ",726,834);
$z[1][4]=array();
$z[1][4]['typeid']="4";
$z[2]=Array("type","\r\n				    <li><a href=\"[field:typelink/]\">Baby protective clothing</a></li>\r\n				    ",844,964);
$z[2][4]=array();
$z[2][4]['typeid']="5";
$z[3]=Array("type","\r\n				    <li><a href=\"[field:typelink/]\">Baby underwear</a></li>\r\n				    ",974,1084);
$z[3][4]=array();
$z[3][4]['typeid']="6";
$z[4]=Array("type","\r\n						<div class=\"col-xs-4\"><a href=\"[field:typelink/]\">New products</a></div>\r\n						",2579,2702);
$z[4][4]=array();
$z[4][4]['typeid']="8";
$z[5]=Array("type","\r\n						<div class=\"col-xs-4\"><a href=\"[field:typelink/]\">Baby sweater</a></div>\r\n						",2710,2833);
$z[5][4]=array();
$z[5][4]['typeid']="4";
$z[6]=Array("type","\r\n						<div class=\"col-xs-4\"><a href=\"[field:typelink/]\">Baby protective clothing</a></div>\r\n						",2841,2976);
$z[6][4]=array();
$z[6][4]['typeid']="5";
$z[7]=Array("type","\r\n						<div class=\"col-xs-4\"><a href=\"[field:typelink/]\">Baby underwear</a></div>\r\n						",2984,3109);
$z[7][4]=array();
$z[7][4]['typeid']="6";

?>